services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - portfolio_data:/app/data
    environment:
      - FLASK_ENV=development
      - PORTFOLIO_PATH=/app/data/portfolio.json
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
    restart: unless-stopped

volumes:
  portfolio_data: